---
.packet:
  extends: .job-moderated
  interruptible: true
  before_script:
    - ./tests/scripts/rebase.sh
    - mkdir -p cluster-dump
  script:
    - ./tests/scripts/testcases_run.sh
  variables:
    ANSIBLE_TIMEOUT: "120"
    CI_PLATFORM: packet
    SSH_USER: kubespray
  tags:
    - ffci
  needs:
    - pipeline-image
    - ci-not-authorized

# TODO: generate testcases matrixes from the files in tests/files/
# this is needed to avoid the need for PR rebasing when a job was added or remvoed in the target branch
# (currently, a removed job in the target branch breaks the tests, because the
# pipeline definition is parsed by gitlab before the rebase.sh script)
# CI template for PRs
packet_pr:
  stage: deploy-part1
  rules:
    - if: $PR_LABELS =~ /.*ci-short.*/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH =~ /^pr-.*$/
      when: on_success
    - when: manual
      allow_failure: true
  extends: .packet
  parallel:
    matrix:
      - TESTCASE:
          - almalinux8-calico
          - almalinux9-crio
          - almalinux9-kube-ovn
          - debian11-calico-collection
          - debian11-macvlan
          - debian12-cilium
          - openeuler24-calico
          - opensuse-docker-cilium
          - rockylinux8-calico
          - rockylinux9-cilium
          - ubuntu20-calico-all-in-one-hardening
          - ubuntu20-cilium-sep
          - ubuntu22-calico-all-in-one
          - ubuntu22-calico-all-in-one-upgrade
          - ubuntu24-calico-etcd-datastore

# The ubuntu20-calico-all-in-one jobs are meant as early stages to prevent running the full CI if something is horribly broken
packet_ubuntu20-calico-all-in-one:
  stage: deploy-part1
  extends: .packet
  variables:
    TESTCASE: ubuntu20-calico-all-in-one
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^pr-.*$/
      when: on_success
    - when: manual
      allow_failure: true

packet_pr_full:
  extends: .packet
  stage: deploy-extended
  rules:
    - if: $PR_LABELS =~ /.*ci-full.*/
      when: on_success
    # Else run as manual
    - when: manual
      allow_failure: true
  parallel:
    matrix:
      - TESTCASE:
          - almalinux9-calico-ha-ebpf
          - almalinux9-calico-nodelocaldns-secondary
          - debian11-custom-cni
          - debian11-kubelet-csr-approver
          - debian12-custom-cni-helm
          - fedora39-calico-swap-selinux
          - fedora39-crio
          - ubuntu20-all-in-one-docker
          - ubuntu20-calico-ha-wireguard
          - ubuntu20-flannel-ha
          - ubuntu20-flannel-ha-once

# Need an update of the container image to use schema v2
# update: quay.io/kubespray/vm-amazon-linux-2:latest
packet_manual:
  extends: packet_pr_full
  parallel:
    matrix:
      - TESTCASE:
          - amazon-linux-2-all-in-one
  rules:
    - when: manual
      allow_failure: true

packet_pr_extended:
  extends: .packet
  stage: deploy-extended
  rules:
    - if: $PR_LABELS =~ /.*(ci-extended|ci-full).*/
      when: on_success
    - when: manual
      allow_failure: true
  parallel:
    matrix:
      - TESTCASE:
          - almalinux9-calico
          - almalinux9-calico-remove-node
          - almalinux9-docker
          - debian11-docker
          - debian12-calico
          - debian12-docker
          - rockylinux9-calico
          - ubuntu20-calico-etcd-kubeadm
          - ubuntu22-all-in-one-docker
          - ubuntu24-all-in-one-docker
          - ubuntu24-calico-all-in-one

# Enabled when PERIODIC_CI_ENABLED var is set
packet_periodic:
  only:
    variables:
      - $PERIODIC_CI_ENABLED
  allow_failure: true
  extends: .packet
  parallel:
    matrix:
      - TESTCASE:
          - debian11-calico-upgrade
          - debian11-calico-upgrade-once
          - debian12-cilium-svc-proxy
          - fedora39-calico-selinux
          - fedora40-docker-calico
          - ubuntu20-calico-etcd-kubeadm-upgrade-ha
          - ubuntu20-calico-ha-recover
          - ubuntu20-calico-ha-recover-noquorum
